Galileo\SettingBundle\Entity\Setting:
    type: entity
    table: galileo_settings_setting
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        value:
            type: text
        section:
            type: string
            length: 255
    uniqueConstraints:
        unique_name_within_section:
          columns: [ name, section ]
